id_to_remove = list(['alignment',
                  'treeModel',
                  'treeLength',
                  'CP1+2.patterns',
                  'CP3.patterns',
                  'initialDemo',
                  'age(root)',
                  'skygrid',
                  'branchRates',
                  'meanRate',
                  'coefficientOfVariation',
                  'covariance',
                  'CP1+2.hky',
                  'CP3.hky',
                  'CP1+2.siteModel',
                  'CP3.siteModel',
                  'allMus',
                  'treeLikelihood',
                  "startingTree"])

params_to_remove = list(['CP1+2.kappa',
                         'CP3.kappa',
                         'frequencies',
                         'CP1+2.alpha',
                         'CP3.alpha',
                         'ucld.mean',
                         'ucld.stdev',
                         'treeModel.allInternalNodeHeights',
                         'ucld.mean',
                         'branchRates.categories',
                         'allMus',
                         'treeModel.rootHeight',
                         'treeModel.internalNodeHeights',
                         'skygrid.precision',
                         'ucld.mean',
                         'ucld.stdev',
                         'skygrid.logPopSize',
                         'skygrid.cutOff',
                         'skygrid',
                         "age(root)"])

others_to_remove = list(['upDownOperator',
                         'subtreeSlide',
                         'narrowExchange',
                         'wideExchange',
                         'wilsonBalding',
                         'gmrfGridBlockUpdateOperator',
                         'trancated',
                         'gmrfSkyGridLikelihood',
                         'treeDataLikelihood',
                         'discretizedBranchRates'])

keys = [['', 'id', 'alignment'],
        ['', 'id', 'treeModel'],
        ['', 'id', 'treeLength'],
        ['', 'id', 'CP1+2.patterns'],
        ['', 'id', 'CP3.patterns'],
        ['', 'id', 'initialDemo'],
        ['', 'id', 'age(root)'],
        ['', 'id', 'skygrid'],
        ['', 'id', 'branchRates'],
        ['', 'id', 'meanRate'],
        ['', 'id', 'coefficientOfVariation'],
        ['', 'id', 'covariance'],
        ['', 'id', 'CP1+2.hky'],
        ['', 'id', 'CP3.hky'],
        ['', 'id', 'CP1+2.siteModel'],
        ['', 'id', 'CP3.siteModel'],
        ['', 'id', 'allMus'],
        ['', 'id', 'treeLikelihood'],
        ['', 'id', "startingTree"],
        ['parameter', 'idref', 'CP1+2.kappa'],
        ['parameter', 'idref', 'CP3.kappa'],
        ['parameter', 'idref', 'frequencies'],
        ['parameter', 'idref', 'CP1+2.alpha'],
        ['parameter', 'idref', 'CP3.alpha'],
        ['parameter', 'idref', 'ucld.mean'],
        ['parameter', 'idref', 'ucld.stdev'],
        ['parameter', 'idref', 'treeModel.allInternalNodeHeights'],
        ['parameter', 'idref', 'ucld.mean'],
        ['parameter', 'idref', 'branchRates.categories'],
        ['parameter', 'idref', 'allMus'],
        ['parameter', 'idref', 'treeModel.rootHeight'],
        ['parameter', 'idref', 'treeModel.internalNodeHeights'],
        ['parameter', 'idref', 'skygrid.precision'],
        ['parameter', 'idref', 'ucld.mean'],
        ['parameter', 'idref', 'ucld.stdev'],
        ['parameter', 'idref', 'skygrid.logPopSize'],
        ['parameter', 'idref', 'skygrid.cutOff'],
        ['parameter', 'idref', 'skygrid'],
        ['parameter', 'idref', "age(root)"],
        ['tmrcaStatistic', 'idref', "age(root)"],
        ['discretizedBranchRates', 'idref', "branchRates"],
        ['upDownOperator', '', ''],
        ['subtreeSlide', '', ''],
        ['narrowExchange', '', ''],
        ['wideExchange', '', ''],
        ['wilsonBalding', '', ''],
        ['gmrfGridBlockUpdateOperator', '', ''],
        ['trancated', '', ''],
        ['gmrfSkyGridLikelihood', '', ''],
        ['treeDataLikelihood', '', ''],
        ['discretizedBranchRates', '', '']
        ]
