library(tidyverse)
geodata <- read_csv('./gdam_geodata.csv')

test <- metadata_unformatted %>% bind_rows(., .id = 'ref')

if('location_2' %in% colnames(data)){
  test <- test %>%
    # Format source before taxa allocation
    rename(joint_location = location) %>%
    mutate(across(contains('location'), 
                  .fns = ~ gsub("^NA$|^missing$|^unknown$", NA, .x))) %>%
    mutate(location = coalesce(location_3,location_2)) %>%
    select(-joint_location)%>%
    rename(source=host) %>%
    select(-starts_with('host')) %>%
    rename(month.date = date_year_month) %>%
    rename(decimal.date = date_frac)
  
} else{
 test <- test %>%
    mutate(date = parsedate::parse_date(date) %>%
             as.Date()) %>%
    mutate(decimal.date = format(round(decimal_date(date), 2), 
                                 nsmall = 2) ) %>%
    mutate(decimal.date = suppressWarnings(as.double(decimal.date))) %>%
    mutate(month.date = format(date, "%Y-%m"))
}

test <- test %>%
  select(-matches('^date.+')) %>%
  rename_with(.fn = ~gsub('_', '.', .x))%>%
  # Location (iso name and subdivision)
  mutate(location = tolower(location)) %>%
  mutate(location = gsub("[^A-Za-z]", " ", tolower(location))) %>%
  mutate(location =  gsub("\\s+", " ", str_trim(location))) %>%
  
  mutate(location = case_when( 
    # Austria
    grepl('burgenland|stegersbach|mattersburg|bad sauerbrunn',
          location) ~ 'austria_burgenland',
    grepl('karnten', 
          location)  ~ 'austria_karnten',
    grepl('niederosterreich|voesendorf|strasshof|stockerau|sollenau|breitensee|biberbach',
          location) ~ "austria_niederösterreich", 
    grepl('sankt poelten|pottschach|neunkirchen|markgrafneusiedl|koenigstetten|klosterneuburg',
          location) ~ "austria_niederösterreich",
    grepl('hof am leithaberge|haringsee|fishamend|bruderndorf|tulln|lower austria',
          location) ~ "austria_niederösterreich",
    grepl('oberosterreich$|sankt georgen|^linz$|oberneukirchen',
          location) ~ "austria_oberösterreich",
    grepl('salzburg', 
          location)  ~ 'austria_salzburg',
    grepl('steiermark|tagnitz|^graz$|eggersdorf|leibnitz', 
          location) ~ "austria_steiermark",
    grepl('tirol$', 
          location)  ~ 'austria_tirol',
    grepl('vorarlberg|voralrberg', 
          location)  ~ "austria_vorarlberg",
    grepl('^wien$|^vienna$|bundesland wien', 
          location) ~ 'austria_wien',
    grepl('carinthia', 
          location) ~ "austria_kärnten",
    
    # Belgium
    grepl('antwerpen',
          location) ~ "austria_antwerpen",
    grepl("brabant wallon",
          location) ~ "austria_brabant wallon",
    grepl("brussels capital region|region de bruxelles capitale",
          location) ~ "austria_brussels-capital region",
    grepl('*hainaut$',
          location) ~ "austria_hainaut",
    grepl('*liege$',
          location) ~ "austria_liege",
    grepl('limburg',
          location) ~ "austria_limburg",
    grepl(' luxembourg', 
          location) ~ "austria_luxembourg",
    grepl("^namur$|province de namur",
          location) ~ "austria_namur",
    grepl('oost vlaanderen',
          location) ~ "austria_oost-vlaanderen",
    grepl('vlaams brabant', 
          location) ~ "austria_vlaams-brabant",
    grepl('west vlaanderen', 
          location) ~ "austria_west-vlaanderen",
    
    # Bulgaria 
    grepl('blagoevgrad', 
          location) ~ "bulgaria_blagoevgrad",
    grepl('burgas$', 
          location) ~ "bulgaria_burgas",
    grepl('dobrich$', 
          location) ~ "bulgaria_dobrich",
    grepl('gabrovo$', 
          location) ~ "bulgaria_gabrovo",
    grepl('haskovo$', 
          location) ~ "bulgaria_haskovo",
    grepl('kardzhali$', 
          location) ~ "bulgaria_kardzhali",
    grepl('kyustendil$', 
          location) ~ "bulgaria_kyustendil",
    grepl('lovech$', 
          location) ~ "bulgaria_lovech",
    grepl('blagoevgrad', 
          location) ~ "bulgaria_blagoevgrad",
    grepl('"pazardzhik"', 
          location) ~ "bulgaria_pazardzhik",
    grepl('pernik', 
          location) ~ "bulgaria_pernik",
    grepl('pleven|slavyanovo', 
          location) ~ "bulgaria_pleven",
    grepl('plovdiv$', 
          location) ~ "bulgaria_plovdiv",
    grepl('^razgrad$', 
          location) ~ "bulgaria_razgrad",
    grepl('^ruse$', 
          location) ~ "bulgaria_ruse",
    grepl('shumen', 
          location) ~ "bulgaria_shumen",
    grepl('silistra', 
          location) ~ "bulgaria_silistra",
    grepl('sliven', 
          location) ~ "bulgaria_sliven",
    grepl('smolyan', 
          location) ~ "bulgaria_smolyan",
    grepl('^sofia$', 
          location) ~ "bulgaria_sofia",
    grepl('sofia-grad', 
          location) ~ "bulgaria_sofia-grad",
    grepl('stara zagora', 
          location) ~ "bulgaria_stara zagora",
    grepl('targovishte', 
          location) ~ "bulgaria_targovishte",
    grepl('varna', 
          location) ~ "bulgaria_varna",
    grepl('veliko tarnovo', 
          location) ~ "bulgaria_veliko tarnovo",
    grepl('^vidin$', 
          location) ~ "bulgaria_vidin",
    grepl('^vratsa$', 
          location) ~ "bulgaria_vratsa",
    grepl('^yambol$', 
          location) ~ "bulgaria_yambol",
    
    # Burkina Faso
    grepl("koubri", 
          location) ~ "burkina faso_kadiogo",
    grepl("gomboussougou", 
          location) ~ "burkina faso_zoundwéogo",
    
    # Cambodia
    grepl("krong phnum penh", 
          location) ~"cambodia_phnom penh",
    grepl("khett kandal",
          location) ~"cambodia_kandal",
    grepl("khett prey veng",
          location) ~"cambodia_prey veaeng",
    grepl("takeo", 
          location) ~"cambodia_taakaev",
    
    # Chile
    grepl("region de antofagasta", 
          location) ~ "child_antofagasta",
    
    # Colombia
    grepl("departamento de bolivar", 
          location) ~"colombia_bolívar",
    grepl("departamento del choco", 
          location) ~"colombia_chocó",
    grepl("departamento de cordoba",
          location) ~"colombia_córdoba",
    grepl("departamento del magdalena", 
          location) ~"colombia_magdalena",
    
    # Costa Rica
    grepl("provincia de limon",
          location) ~ "costa rica_limón",
    
    # Croatia
    grepl('koprivnicko krizevacka zupanija', 
          location) ~ "croatia_koprivničko-križevačka županija",
    grepl('vukovarsko srijemska zupanija',
          location) ~ "croatia_vukovarsko-srijemska županija",
    grepl('sisacko moslavacka zupanija',
          location) ~ "croatia_sisačko-moslavačka županija",   
    
    # Denmark
    grepl('region sjaland', 
          location) ~    "denmark_sjælland",
    grepl('region syddanmark', 
          location) ~ "denmark_syddanmark",
    grepl('region nordjylland', 
          location) ~ "denmark_nordjylland",
    grepl('region midtjylland',
          location) ~"denmark_midtjylland",
    grepl('*denmark$',
          location) ~ 'denmark',
    
    # Ecuador
    grepl('provincia de manabi', 
          location) ~ "ecuador_manabí",
    
    # Honduras
    grepl('departamento de atlantida',
          location) ~ "honduras_atlántida",
    
    # Hungary
    grepl('bacs kiskun',
          location) ~   "hungary_bács-kiskun",
    grepl('csongrad megye', 
          location) ~ "hungary_csongrád",
    grepl('bekes megye', 
          location) ~ "hungary_békés",
    grepl('hajdu bihar', 
          location) ~ "hungary_hajdú-bihar",
    grepl('somogy megye', 
          location) ~  "hungary_somogy",
    
    # Iceland
    grepl('westfjords',
          location) ~ "iceland_vestfirðir",
    
    # Indonesia
    grepl('east java', 
          location) ~ "indonesia_jawa timur",
    
    # Iraq
    grepl('muhafazat ninawa',
          location) ~ "iraq_ninawa",
    
    # Israel
    grepl('northern district', 
          location) ~ "israel_hazafon",
    
    # Kazakhstan
    grepl('akmola', 
          location) ~ "kazakhstan_aqmola", 
    grepl('kostanay', 
          location) ~ "kazakhstan_qostanay",        
    grepl('soltüstik quzaqstan oblysy|north kazakhstan',
          location) ~ "kazakhstan_north kazakhstan",
    grepl('almaty province', 
          location) ~ "kazakhstan_almaty",
    
    # Latvia
    grepl('jurmala',
          location) ~"latvia_jūrmala",
    # Lithuania
    grepl('vilnius', 
          location) ~"lithuania_vilniaus apskritis",
    # Luxembourg
    grepl('district de grevenmacher', 
          location) ~ "luxembourg_grevenmacher",
    grepl('district de diekirch', 
          location) ~ "luxembourg_diekirch",
    # Mali
    grepl('kati', 
          location) ~ "mali_koulikoro",
    
    # Montenegro
    grepl('skadar lake',
          location) ~ "montenegro_bar",
    
    # Niger
    grepl('bouza tahoua', 
          location) ~ "niger_tahoua",
    grepl('torodi tillab ri',
          location) ~ "niger_tillabéri",  
    grepl(' zinder$', 
          location) ~ "niger_zinder",
    grepl('maradi$',
          location) ~ "niger_maradi",
    grepl('niamey$', 
          location) ~ "niger_niamey",
    
    # Norway
    grepl('hitra', 
          location) ~ "norway_sør-trøndelag",
    grepl('tromso',
          location) ~"norway_troms",
    
    # Peru
    grepl('departamento de lima', 
          location) ~  "peru_municipalidad metropolitana de lima",      
    grepl('provincia constitucional del callao',
          location) ~"peru_el callao",
    grepl('departamento de tacna',
          location) ~ "peru_tacna",        
    grepl('departamento de ica',
          location) ~  "peru_ica",             
    
    # Portugal
    grepl('distrito de setubal', 
          location) ~ "portugal_setúbal",
    
    # Romania
    grepl('judetul timis', 
          location) ~ "romania_timiș",     
    grepl('judetul ilfov', 
          location) ~ "romania_ilfov",      
    grepl('judetul constanta', 
          location) ~ "romania_constanța", 
    grepl('mures ungheni', 
          location) ~ "romania_mureș",     
    grepl('judetul giurgiu', 
          location) ~ "romania_giurgiu",   
    grepl('tulcea',
          location) ~ "romania_tulcea",    
    
    # Senegal
    grepl('region de thies',
          location) ~ 'sengeal_thiès',
    grepl('djoudj bird sanctuary',
          location) ~ 'sengeal_saint-louis',
    
    # Slovakia
    grepl('dobrohost', 
          location) ~ "slovakia_trnavský kraj",
    grepl('kosice',
          location) ~  "slovakia_košický kraj" ,
    grepl('kalinkovo|petrzalka',
          location) ~"slovakia_bratislavský kraj",
    
    # South Africa
    grepl('province of the western cape',
          location) ~ "south africa_western cape",
    grepl('province of kwazulu natal', 
          location) ~  "south africa_kwazulu-natal",
    grepl('province of north west',
          location) ~ "south africa_north west",
    
    # Switzerland
    grepl('*zurich$',
          location) ~ "switzerland_zürich",
    grepl('*ticino$', 
          location) ~ "switzerland_ticino",    
    grepl('kanton basel stadt|*basel$', 
          location) ~ "switzerland_basel-stadt",
    grepl('*luzern$', 
          location) ~ "switzerland_lucerne",
    
    # Venezuela
    grepl("estado anzoategui", 
          location) ~ "venezuela_anzoátegui",
    
    # latin
    grepl('mexico', location) ~ 'méxico',
    grepl('^choco$', location) ~ 'colombia_chocó',
    grepl('valparaiso', location) ~ 'chile_valparaíso',
    grepl('tarapaca', location) ~ 'chile_tarapacá',
    grepl('^nuble$', location) ~ 'chile_ñuble',
    grepl('araucania', location) ~ 'chile_araucanía',
    #grepl("cordoba" , location) ~ 'spain_córdoba',
    grepl('atacama', location) ~ 'chile_atacama',
    grepl('coquimbo', location) ~ 'chile_coquimbo',
    grepl('antofagasta', location) ~ 'chile_antofagasta',
    grepl('maule', location) ~ 'chile_maule',
    grepl('arica y parinacota', location) ~ 'chile_arica y parinacota',
    
    # Vietnam
    grepl("viet nam", 
          location) ~ "vietnam",
    grepl("quang ninh" ,
          location) ~  "vietnam_quảng ninh" ,
    grepl('tinh lang son',
          location) ~ "vietnam_lạng sơn",
    grepl('tinh thanh hoa',
          location) ~ "vietnam_thanh hóa",
    grepl('nghe an|nhge an', 
          location) ~  "vietnam_nghệ an", 
    grepl('tinh quang tri',
          location) ~ "vietnam_quảng trị",
    grepl('nam ha tinh', 
          location) ~ "vietnam_hà tỉnh",
    grepl('thu do ha noi',
          location) ~ "vietnam_hà nội",
    
    # grepl('laos', location) ~ "lao people's democratic republic",
    .default = location)) %>%
  
  mutate(location = case_when(
    # PRC
    grepl("northern china|peking|beijing", 
          location) ~ "china_beijing", # Interpretation from paper - check with Lu
    grepl("chongqin*", 
          location) ~ "china_chongqing",
    grepl("shanghai",
          location) ~ "china_shanghai",
    grepl('tianjing',
          location) ~ 'china_tianjin',
    grepl('anhui',
          location) ~ 'china_anhui',
    grepl('^fujain$|^fujian$', 
          location) ~ 'china_fujian',
    grepl('gansu',
          location) ~ 'china_gansu',
    grepl('qingyuan|foshan|guangdong',
          location) ~ 'china_guangdong',
    grepl('guizhou', 
          location) ~ 'china_guizhou',
    grepl("heinan|hainan", 
          location) ~ "china_hainan", # confirm 
    grepl("wuhan|hebei", 
          location) ~ "china_hebei",
    grepl("heilongjiang", 
          location) ~ "china_heilongjiang",
    grepl("henan|sanmenxia|dongting", 
          location) ~ "china_henan",
    grepl("hubei",
          location) ~ "china_hubei",
    grepl("hunan|changsha", 
          location) ~ "china_hunan",
    grepl("jiangsu|suzhou|xuzhou|^xuyi$",
          location) ~ "china_jiangsu",
    grepl("jiangxi|ganzhou", 
          location) ~ "china_jiangxi",
    grepl("jilin", 
          location) ~ "china_jilin",
    grepl("liaoning",
          location) ~ "china_liaoning",
    grepl("qinghai", 
          location) ~ "china_qinghai",
    grepl("shaanxi", 
          location) ~ "china_shaanxi",
    grepl("shandong|rongcheng", 
          location) ~ "china_shandong",
    grepl("shanxi|southwestern china",
          location) ~ "china_shanxi",
    grepl("sichuan",
          location) ~ "china_sichuan",
    grepl("taiwan|chiayi|taoyuan|pingtung", 
          location) ~ "taiwan",
    grepl("taipei", 
          location) ~ "taiwan_taipei",
    grepl("yunnan.*", 
          location) ~ "china_yunnan",
    grepl("zhejiang|hangzhou|nanji$|eastern china",
          location) ~ "china_zhejiang",
    grepl("guangxi$|guilin|hechi|guangxi zhuang",
          location) ~ "china_guangxi",
    grepl("inner mongolia|tumuji|nei mongol", 
          location) ~ "china_nei mongol",
    grepl("ningxia$|ningxia hui", 
          location) ~ "china_ningxia hui",
    grepl("xinjiang$", 
          location) ~ "china_xinjiang uygur",
    grepl("xizang$|tibet", 
          location) ~ "china_xizang",
    grepl("macau",
          location) ~ "china_macau",
    grepl("hong kong|hongkong",
          location) ~ "china_hong kong",
    
    
    # Canada
    grepl("^ab$",
          location) ~ "canada_alberta",
    grepl("^bc$", 
          location) ~ "canada_british columbia",
    grepl('^mb$', 
          location) ~'canada_manitoba',
    grepl('^pei$',
          location) ~ 'canada_prince edward island',
    grepl('^qc$',
          location) ~ 'canada_québec',
    grepl('^on$',
          location) ~ 'canada_ontario',
    grepl('^sk$',
          location) ~ 'canada_saskatchewan',
    grepl('new brunswick', 
          location) ~ 'canada_new brunswick',
    
    # Czechia
    grepl("jihocesky kraj", 
          location) ~"czechia_jihočeský kraj",
    grepl("south moravian region", 
          location) ~"czechia_jihomoravský kraj",
    grepl("kralovehradecky kraj", 
          location) ~"czechia_královéhradecký kraj",
    grepl("liberecky kraj",
          location) ~"czechia_liberecký kraj",
    grepl("morovskoslezsky kraj", 
          location) ~"czechia_moravskoslezský kraj",
    grepl("olomoucky kraj",
          location) ~"czechia_olomoucký kraj",
    grepl("pardubicky kraj", 
          location) ~"czechia_pardubický kraj",
    grepl("plzensky kraj",
          location) ~"czechia_plzeňský kraj",
    grepl("hlavni mesto praha", 
          location) ~"czechia_praha, hlavní město",
    grepl("stredocesky kraj",
          location) ~"czechia_středočeský kraj",
    grepl("ustecky kraj",
          location) ~"czechia_ústecký kraj",
    grepl("vysocina kraj",
          location) ~"czechia_vysočina",
    grepl("zlinsky kraj",
          location) ~"czechia_zlínský kraj",
    grepl("nov hrady by ov", 
          location) ~"czechia_české budějovice",
    
    
    # France
    grepl("^france&",
          location) ~"france",
    grepl("^alsace&",
          location) ~"france_alsace",
    grepl("aquitaine",
          location) ~"france_aquitaine",
    grepl("auvergne",
          location) ~"france_auvergne",
    grepl("basse normandie",
          location) ~"france_basse-normandie",
    grepl("bourgogne", 
          location) ~"france_bourgogne",
    grepl("brittany",
          location) ~"france_bretagne",
    grepl("^centre$",
          location) ~"france_centre",
    grepl("champagne ardenne",
          location) ~"france_champagne-ardenne",
    grepl("corsica", 
          location) ~"france_corse",
    grepl("franche comté",
          location) ~"france_franche-comté",
    grepl("haute normandie", 
          location) ~"france_haute-normandie",
    grepl("region ile de france",
          location) ~"france_île-de-france",
    grepl("languedoc roussillon", 
          location) ~"france_languedoc-roussillon",
    grepl("limousin", 
          location) ~"france_limousin",
    grepl("region lorraine", 
          location) ~"france_lorraine",
    grepl("midi pyrenees", 
          location) ~"france_midi-pyrénées",
    grepl("region nord pas de calais", 
          location) ~"france_nord - pas-de-calais",
    grepl("region pays de la loire", 
          location) ~"france_pays de la loire",
    grepl("poitou charentes",
          location) ~"france_poitou-charentes",
    grepl("rhone alpes", 
          location) ~"france_rhône-alpes",
    grepl("guadeloupe", 
          location) ~"france_guadeloupe",
    grepl("guyane", 
          location) ~"france_guyane",
    grepl("martinique", 
          location) ~"france_martinique",
    grepl("réunion",
          location) ~"france_réunion",
    grepl("aisne", 
          location) ~"france_aisne",
    grepl("allier",
          location) ~"france_allier",
    
    
    # Italy
    grepl("emilia romagna", 
          location) ~"italy_emilia-romagna",
    grepl("lombardy",
          location) ~"italy_lombardia",
    grepl("^bs$", 
          location) ~"italy_brescia",
    grepl("^cr$", 
          location) ~"italy_cremona",
    grepl("^mn$", 
          location) ~"italy_mantova",
    grepl("^pd$",
          location) ~"italy_padova",
    grepl("^ud$",
          location) ~"italy_udine",
    grepl("^ve$", 
          location) ~"italy_venezia",
    grepl("^vr$", 
          location) ~"italy_verona",
    grepl("^vi$", 
          location) ~"italy_vicenza",
    
    # Kosovo (Currently represented as serbia)
    grepl('gjilan',
          location) ~ "kosovo_gnjilane",  
    grepl('mitrovice|mitrovica', 
          location) ~ "kosovo_kosovska mitrovica",
    # grepl('shtime|rahovec|malisheve',
    #  location) ~ "pećki okrug",
    # grepl('kacanik|ferizaj|shtime|suhareke',
    # location) ~ "kosovski okrug",
    grepl('kosovo', 
          location) ~   "kosovo",
    
    # Russian Federation
    grepl('russian federation', 
          location) ~ 'russia',
    grepl('khabarovsk', 
          location) ~ "russia_khabarovsk",
    grepl('chelyabinsk', 
          location) ~ "russia_chelyabinsk",
    grepl("astrakhan", 
          location) ~ "russia_astrakhan'",
    grepl("novosibirsk|chany lake|^chany$", 
          location) ~ "russia_novosibirsk",
    grepl("^omsk*|russia omsk region|russia omsk", 
          location) ~ "russia_omsk",
    grepl("rostov oblast|rostov on don|^rostov$", 
          location) ~ "russia_rostov",
    grepl("russia primorje", 
          location) ~ "russia_primor'ye",
    grepl("sakhalin", 
          location) ~ "russia_sakhalin",
    grepl("yakutia", 
          location) ~ "russia_sakha",
    grepl("kostrom*", 
          location) ~ "russia_kostroma",
    grepl("amur region", 
          location) ~ "russia_amur",
    grepl("buryatia", 
          location) ~ "russia_buryat",
    grepl('north ossetia-alania', 
          location) ~ 'russia_north ossetia',
    grepl('dagestan', 
          location) ~ 'russia_dagestan',
    grepl('stavropol', 
          location) ~ "russia_stavropol'",
    grepl('krasnodar', 
          location) ~ "russia_krasnoyarsk", 
    grepl('tyumen|tumen', 
          location) ~ "russia_tyumen'",
    grepl("magadan",
          location) ~ "russia_magadan",
    grepl('saratov', 
          location) ~ "russia_saratov",
    grepl('kurgan*', 
          location) ~ "russia_kurgan",
    grepl('central russia',
          location) ~ 'russia',
    grepl('republic of tatarstan|^tatarstan$', 
          location) ~"russia_tatarstan",
    grepl('republic of kalmykia|^kalmykia$', 
          location) ~ "russia_kalmyk",
    grepl('siberia', 
          location) ~ "russia_krasnoyarsk",
    
    grepl('^tuva$|^tyva$|uvs nuur lake', 
          location) ~ "russia_tuva",
    
    grepl('kaliningra{0,1}d', 
          location) ~ "russia_kaliningrad",
    grepl('cheboksary', 
          location) ~ "russia_chuvash",
    grepl('kursk', 
          location) ~ "russia_kursk",
    grepl('sergiyev[[:space:]]{0,1}posad|shchyolkovo|moscow|chernogolovka', 
          location) ~ "russia_moskva",
    grepl('kamchatka', 
          location) ~ 'russia_kamchatka',
    grepl('voronezh', 
          location) ~ "russia_voronezh",
    grepl('^orel$', 
          location) ~ "russia_orel",
    grepl('^penza$', 
          location) ~ "russia_penza",
    grepl('^samara$', 
          location) ~ "russia_samara",
    grepl('^mari el$', 
          location) ~ 'russia_mariy-el',
    grepl('^leningrad$|leningrad region', 
          location) ~ "russia_leningrad",
    grepl('^orenburg$', 
          location) ~ "russia_orenburg",
    grepl('^ryazan$', 
          location) ~ "russia_ryazan'",
    grepl('^altai$', 
          location) ~ 'russia_altay',
    
    #morocco
    grepl('^fes$', 
          location) ~ 'morocco_fès - boulemane',
    grepl('^casablanca$', 
          location) ~ 'morocco_grand casablanca',
    grepl('^kenitra$', 
          location) ~ 'morocco_rabat - salé - zemmour - zaer',
    grepl('^nador$', 
          location) ~ 'morocco_oriental',
    
    
    # Egypt
    grepl('^luxor$', 
          location) ~ 'egypt_qina',
    grepl('^cairo$', 
          location) ~ 'egypt_al qahirah',
    grepl('al sharqia', 
          location) ~ 'egypt_ash sharqiyah',
    grepl('el wadialgidid', 
          location) ~ 'egypt_al wadi al jadid',
    
    
    # USA
    grepl("north dakota",
          location) ~ "united states_north dakota",
    grepl("massachussetts|conneticut|connecticut",
          location) ~"united states_connecticut",
    grepl("massachusetts",
          location) ~"united states_massachusetts",
    grepl("deleware|delaware", 
          location) ~"united states_delaware",
    grepl('^usa$', location) ~ 'united states',
    grepl('alaska$', location) ~ 'united states_alaska',
    grepl("lou[i]{0,1}siana", location) ~ 'united states_louisiana',
    grepl('alabama', location) ~ 'united states_alabama',
    grepl('arizona', location)~ 'united states_arizona',
    grepl('arkansas', location)~ 'united states_arkansas',
    grepl('california', location)~ 'united states_california',
    grepl('colorado', location)~ 'united states_colorado',
    grepl('district of columbia', location)~ 'united states_district of columbia',
    grepl('florida', location)~ 'united states_florida',
    grepl('georgia', location)~ 'united states_georgia',
    grepl('hawaii', location)~ 'united states_hawaii',
    grepl('idaho', location)~ 'united states_idaho',
    grepl('illinois', location)~ 'united states_illinois',
    grepl('indiana', location)~ 'united states_indiana',
    grepl('iowa', location)~ 'united states_iowa',
    grepl('kansas', location)~ 'united states_kansas',
    grepl('kentucky', location)~ 'united states_kentucky',
    grepl('maine', location)~ 'united states_maine',
    grepl( 'maryland', location)~ 'united states_maryland',
    grepl('massachusetts', location)~ 'united states_massachusetts',
    grepl('michigan', location)~ 'united states_michigan',
    grepl('minnesota', location)~ 'united states_minnesota',
    grepl('mississippi', location)~ 'united states_mississippi',
    grepl('missouri', location)~ 'united states_missouri',
    grepl('montana', location)~ 'united states_montana',
    grepl('nebraska', location)~ 'united states_nebraska',
    grepl('nevada', location)~ 'united states_nevada',
    grepl('new hampshire', location)~ 'united states_new hampshire',
    grepl('new jersey', location)~ 'united states_new jersey',
    grepl('new mexico', location)~ 'united states_new mexico',
    grepl('new york', location)~ 'united states_new york',
    grepl('north carolina', location)~ 'united states_north carolina',
    grepl('ohio', location)~ 'united states_ohio',
    grepl('oklahoma', location)~ 'united states_oklahoma',
    grepl('oregon', location)~ 'united states_oregon',
    grepl('pennsylvania', location)~ 'united states_pennsylvania',
    grepl('rhode island', location)~ 'united states_rhode island',
    grepl('south carolina', location)~ 'united states_south carolina',
    grepl('south dakota', location)~ 'united states_south dakota',
    grepl('tennessee', location)~ 'united states_tennessee',
    grepl('texas', location)~ 'united states_texas',
    grepl('utah', location)~ 'united states_utah',
    grepl('vermont', location)~ 'united states_vermont',
    grepl('virginia', location)~ 'united states_virginia',
    grepl('washington', location)~ 'united states_washington',
    grepl('west virginia', location)~ 'united states_west virginia',
    grepl('wisconsin', location)~ 'united states_wisconsin',
    grepl('wyoming', location)~ 'united states_wyoming',
    
    # UK
    grepl("wales",
          location) ~ "united kingdom_wales",
    grepl("england|barrow|northern ireland",
          location) ~ "united kingdom",
    grepl("county of kent", 
          location) ~ "united kingdom_kent",
    grepl("county borough of wrexham", 
          location) ~ "wrexham;wrecsam",
    grepl("stratford", 
          location) ~ "warwickshire",
    grepl("anglesey",
          location) ~ "isle of anglesey;sir ynys môn",
    grepl("orkney", 
          location) ~ "orkney islands",
    grepl("western isles",
          location) ~ "highland",
    grepl("cheshire", 
          location) ~ "cheshire east",
    grepl("scotland",
          location) ~ "united kingdom_scotland",
    
    # Japan
    grepl('aichi', 
          location) ~ 'japan_aichi',
    grepl('akita', 
          location) ~ 'japan_akita',
    grepl('aomori', 
          location) ~ 'japan_aomori',
    grepl('chiba', 
          location) ~ 'japan_chiba',
    grepl('ehime', 
          location) ~ 'japan_ehime',
    grepl('fukui', 
          location) ~ 'japan_fukui',
    grepl('fukuoka', 
          location) ~ 'japan_fukuoka',
    grepl('fukushima', 
          location) ~ 'japan_fukushima',
    grepl('gifu', 
          location) ~ 'japan_gifu',
    grepl('gunma', 
          location) ~ 'japan_gunma',
    grepl('hiroshima', 
          location) ~ 'japan_hiroshima',
    grepl('hokkaido', 
          location) ~ 'japan_hokkaido',
    grepl('hyogo|hyōgo', 
          location) ~ 'japan_hyōgo',
    grepl('tsukuba|ibaraki', 
          location) ~ 'japan_ibaraki',
    grepl('ishikawa', 
          location) ~ 'japan_ishikawa',
    grepl('iwate', 
          location) ~ 'japan_iwate',
    grepl('kagawa', 
          location) ~ 'japan_kagawa',
    grepl('kagoshima', 
          location) ~ 'japan_kagoshima',
    grepl('kanagawa', 
          location) ~ 'japan_kanagawa',
    grepl('kochi', 
          location) ~ 'japan_kochi',
    grepl('kumamoto', 
          location) ~ 'japan_kumamoto',
    grepl('kyoto', 
          location) ~ 'japan_kyoto',
    grepl('mie', 
          location) ~ 'japan_mie',
    grepl('miyagi', 
          location) ~ 'japan_miyagi',
    grepl('miyazaki', 
          location) ~ 'japan_miyazaki',
    grepl('nagano', 
          location) ~ 'japan_nagano',
    grepl('nagasaki|naoasaki', 
          location) ~ 'japan_naoasaki',
    grepl('nara', 
          location) ~ 'japan_nara',
    grepl('niigata', 
          location) ~ 'japan_niigata',
    grepl('oita', 
          location) ~ 'japan_oita',
    grepl('okayama', 
          location) ~ 'japan_okayama',
    grepl('okinawa', 
          location) ~ 'japan_okinawa',
    grepl('osaka', 
          location) ~ 'japan_osaka',
    grepl('saga', 
          location) ~ 'japan_saga',
    grepl('saitama', 
          location) ~ 'japan_saitama',
    grepl('shiga', 
            location) ~ 'japan_shiga',
    grepl('shimane', 
          location) ~ 'japan_shimane',
    grepl('shizuoka', 
          location) ~ 'japan_shizuoka',
    grepl('tochigi', 
          location) ~ 'japan_tochigi',
    grepl('tokushima', 
          location) ~ 'japan_tokushima',
    grepl('tokyo', 
          location) ~ 'japan_tokyo',
    grepl('tottori', 
          location) ~ 'japan_tottori',
    grepl('toyama', 
          location) ~ 'japan_toyama',
    grepl('wakayama', 
          location) ~ 'japan_wakayama',
    grepl('yamagata', 
          location) ~ 'japan_yamagata',
    grepl('yamaguchi', 
          location) ~ 'japan_yamaguchi',
    grepl('yamanashi', 
          location) ~ 'japan_yamanashi',
    # Spain
    grepl("castilla[ ]{0,1}la[ ]{0,1}mancha|castille[ ]{0,1}la[ ]{0,1}mancha",
          location) ~ "spain_castilla-la mancha",
    
    # Poland
    grepl("lower silesian voivodeship", 
          location) ~"poland_dolnośląskie",
    grepl("kuyavian pomeranian voivodeship",
          location) ~"poland_kujawsko-pomorskie",
    grepl("lublin voivodeship", 
          location) ~"poland_lubelskie",
    grepl("lubusz voivodeship",
          location) ~"poland_lubuskie",
    grepl("lodzkie|odz voivodeship",
          location) ~"poland_łódzkie",
    grepl("lesser poland voivodeship", 
          location) ~"poland_małopolskie",
    grepl("masovian voivodeship",
          location) ~"poland_mazowieckie",
    grepl("opole voivodeship", 
          location) ~"poland_opolskie",
    grepl("pomeranian voivodeship",
          location) ~"poland_pomorskie",
    grepl("silesian voivodeship", 
          location) ~"poland_śląskie",
    grepl("swietokrzyskie voivodeship", 
          location) ~"poland_świętokrzyskie",
    grepl("warmi sko mazurskie",
          location) ~"poland_warmińsko-mazurskie",
    grepl("greater poland voivodeship", 
          location) ~"poland_wielkopolskie",
    grepl("west pomeranian voivodeship",
          location) ~"poland_zachodniopomorskie",
    
    
    # Sweden
    grepl("blekinge lan",
          location) ~"sweden_blekinge län",
    grepl("dalarnas lan",
          location) ~"sweden_dalarnas län",
    grepl("gotlands lan",
          location) ~"sweden_gotlands län",
    grepl("hallands lan", 
          location) ~"sweden_hallands län",
    grepl("jonkopings lan", 
          location) ~"sweden_jönköpings län",
    grepl("kalmar lan",
          location) ~"sweden_kalmar län",
    grepl("skane lan",
          location) ~"sweden_skåne län",
    grepl("stockholms lan",
          location) ~"sweden_stockholms län",
    grepl("sodermanlands lan", 
          location) ~"sweden_södermanlands län",
    grepl("uppsala lan", 
          location) ~"sweden_uppsala län",
    grepl("vastra gotalands lan",
          location) ~"sweden_västra götalands län",
    grepl("ostergotlands lan", 
          location) ~"sweden_östergötlands län",
    
    
    # Germany 
    grepl("^germany$", 
          location) ~"germany",
    grepl("germany[- ]bw|baden wuerttemberg|freiburg im breisgau|rosengarten|stutensee",
          location) ~"germany_baden-württemberg",
    grepl("germany[- ]by|bavaria|munich|nuremberg|wuerzburg", 
          location) ~"germany_bayern",
    grepl("germany[- ]hb", 
          location) ~"germany_bremen",
    grepl("germany[- ]hh", 
          location) ~"germany_hamburg",
    grepl("germany[- ]he|hessen|freigericht|giessen|karben|ranstadt", 
          location) ~"germany_hessen",
    grepl("germany[- ]ni|lower saxony|brietlingen|dinklage|hannover|lueneburg|nordhorn|osnabruck",
          location) ~"germany_niedersachsen", 
    grepl("osterholz[- ]scharnbeck|theene|wingst",
          location) ~"germany_niedersachsen",
    grepl("germany[- ]nw|north rhine[- ]westphalia|aachen|brueggen", 
          location) ~"germany_nordrhein-westfalen",
    grepl("germany[- ]rp|rhineland[- ]palatinate", 
          location) ~"germany_rheinland-pfalz",
    grepl("germany[- ]sl", 
          location) ~"germany_saarland",
    grepl("germany[- ]sh|schleswig[- ]holstein|aumuehle|brickeln|luebeck|pinneberg|prohn", 
          location) ~"germany_schleswig-holstein",
    grepl("germany[- ]be",
          location) ~"germany_berlin",
    grepl("germany[- ]bb", 
          location) ~"germany_brandenburg",
    grepl("germany[- ]mv|mecklenburg[- ]vorpommern|grevesmuehlen|parchim|ruegen|warin", 
          location) ~"germany_mecklenburg-vorpommern",
    grepl("germany[- ]sn|sachsen|doberschuetz|dresden|gross dueben|leipzig|saxony",
          location) ~"germany_sachsen",
    grepl("germany[- ]st|sachsen[- ]anhalt|^halle$|zeitz", 
          location) ~"germany_sachsen-anhalt",
    grepl("germany[- ]th|thuring.*|^gera$", 
          location) ~"germany_thüringen",
    
    
    # Korea
    grepl("korea", 
          location) ~ "south korea",
    grepl('^gg$|gyeonggi*', 
          location) ~ "south korea_gyeonggido",
    grepl('^gw$', 
          location) ~ "south korea_gang'weondo",
    grepl('^cn$|chungcheongnam*', 
          location) ~ "south korea_chungcheongnamdo",
    grepl('^cb$|chungcheongbuk*',
          location) ~ "south korea_chungcheongbukdo",
    grepl('^gn$',
          location) ~ "south korea_gyeongsangnamdo",
    grepl('^gb$',
          location) ~ "south korea_gyeongsangbukdo",
    grepl('^jn$',
          location) ~ "south korea_jeonranamdo",
    grepl('^jb$', 
          location) ~ "south korea_jeonrabukdo",
    grepl('^jj$',
          location) ~ "south korea_jejudo",
    grepl('^sw$', 
          location) ~ "south korea_seoul teugbyeolsi", 
    grepl('^ic$',
          location) ~ "south korea_incheon gwang'yeogsi", 
    grepl('^dj$',
          location) ~ "south korea_daejeon gwang'yeogsi", 
    grepl('^sj$|sejong teugbyeolsi', 
          location) ~ "south korea_sejong teugbyeolsi", 
    grepl('^gj$',
          location) ~ "south korea_gwangju gwang'yeogsi", 
    grepl('^dg$',
          location) ~ "south korea_daegu gwang'yeogsi", 
    grepl('^ps$', 
          location) ~ "south korea_busan gwang'yeogsi", 
    grepl('^us$', 
          location) ~ "south korea_ulsan gwang'yeogsi", 
    
    
    # Netherlands
    grepl('drenthe|westerveld|borger-odoorn|tynaarlo|eext|koekange|middendrexhe|noordenveld|nl assen',
          location)  ~ 'netherlands_drenthe',
    grepl('flevoland|almere|lelystad|noordoostpolder|noordosterpolder|marker wadden|stroe waddenkust',
          location) ~ 'netherlands_flevoland',
    grepl('zeewolde tulpeiland|zuidlaarmeergebiede oost polder|roggebotsluis|zeewolde',
          location) ~ 'netherlands_flevoland',
    grepl('friesland|fryslan|tytsjerksteradiel|eastermar|heerenveen|schiermonnikoog|^ameland$', 
          location) ~ "netherlands_fryslân",
    grepl('kollum|^vlieland.*|ameland|noord[[:space:]]{0,1}buren waddenkust|greonterp|walterswald|nl abbega|terschelling|leeuwarden', 
          location) ~ "netherlands_fryslân",
    grepl('gelderland|zutphen|zevenaar|westvoort|westervoort|andelst|arnhem|bennekom|deliemers',
          location) ~ 'netherlands_gelderland',
    grepl('spijk|doetichem|doetinchem|epe|ermelo|gelmonde|ingen|klarenbeek|lochem|oldenbroek|huissen',
          location) ~ 'netherlands_gelderland',
    grepl('putten|zwolle bergkloosterweg|apeldoorn boogschutterstraat|boven leeuwen|barneveld',
          location) ~ 'netherlands_gelderland',
    grepl('groningen|zuidhorn|oldambt|spijk|lauwersmeer|haren boeremapark|scheemda|sint annen', 
          location)  ~ 'netherlands_groningen',
    grepl('limburg|venlo|gennep|kerkrade|landgraaf|ottersum|maastricht',
          location) ~ 'netherlands_limburg',
    grepl('noord brabant|wernhout|vlijmen|beekendonk|best|boekel|uden|agatha|schaik|rosmalen|^reek&',
          location) ~ 'netherlands_noord-brabant',
    grepl('lierop|oss|north brabant|oirschot|lithse eendenkooi|werkendam',
          location) ~ 'netherlands_noord-brabant',
    grepl('noord holland|bloemendaal|heerhugowaard|hilversum|huizen|naarden|reek|texel de schorren|volendam|durgerdam', 
          location) ~ 'netherlands_noord-holland',
    grepl('wie[r]{0,1}ingerwerf|den oever|hippolytushoef|kreupel|onderdijk|^obdam$|monnickendam|slootdorp|zuidoost beemster', 
          location) ~ 'netherlands_noord-holland',
    grepl('ijmuiden forteiland|zwaagdijk.*|schellinkhout zuiderdijk|schagen schagerweg|nl wormer$|west graftdijk|oostwoud', 
          location) ~ 'netherlands_noord-holland',
    grepl('overijssel|wierden|enschede|hardenberg|heino|losser|overdinkel|raalte|ijsselmuiden|nl zwolle|kamperveen|mastenbroek',
          location)  ~ 'netherlands_overijssel',
    grepl('utrecht|bilthoven|bosch en duin|bunnik|debilt|derondevenen|soest|haarzuilens|houten|rhenen', 
          location)  ~ 'netherlands_utrecht',
    grepl('ijsselstein|langbroek|nieuwegein|ijsselstein|woerden|leusden|vleuten.*|portengen|eemmeer dode hond|vianen', 
          location)  ~ 'netherlands_utrecht',
    grepl('zeeland|terneuzen|reimerswaal|grenspad|middelburg|weversinlaag|weversinlaag|neeltje jans', 
          location) ~ 'netherlands_zeeland',
    grepl('walcheren t vroon westkapelle|sloehaven', 
          location) ~ 'netherlands_zeeland',
    grepl('zuid holland|zoeterwoude|westland|den haag|rotterdam|rijswijk|leiden|oud albas|oud alblas',
          location) ~ 'netherlands_zuid-holland',
    grepl('nederlek|hardinxveldgiessendam|south holland|eendenkooi stolwijk|haringvliet|bliek$', 
          location) ~ 'netherlands_zuid-holland',
    grepl('kwade hoek stellendam|stellendam scheelhoekeiland|leidschendam|nl gouda|groot ammers|reeuwijk|stolwijk', 
          location) ~ 'netherlands_zuid-holland',
    grepl('^nl$|nl sovon', location) ~ 'netherlands',
    
    
    # Nigeria
    grepl("abuja",
          location) ~"nigeria_abuja capital territory",
    grepl("abia state", 
          location) ~"nigeria_abia",
    grepl("adamawa state",
          location) ~"nigeria_adamawa",
    grepl("akwa ibom state", 
          location) ~"nigeria_akwa ibom",
    grepl("aguata lga|anambra state",
          location) ~"nigeria_anambra",
    grepl("tilden fulani toro lga|bauchi state", 
          location) ~"nigeria_bauchi",
    grepl("bayelsa state", 
          location) ~"nigeria_bayelsa",
    grepl("benue state", 
          location) ~"nigeria_benue",
    grepl("borno state", 
          location) ~"nigeria_borno",
    grepl("corss river state", 
          location) ~"nigeria_cross river",
    grepl("delta state",
          location) ~"nigeria_delta",
    grepl("ebonyi state", 
          location) ~"nigeria_ebonyi",
    grepl("benin edo|edo state", 
          location) ~"nigeria_edo",
    grepl("ekiti state",
          location) ~"nigeria_ekiti",
    grepl("enugu state", 
          location) ~"nigeria_enugu",
    grepl("gombe state|pantaini lbm|^akko[ gombe]{0,1}", 
          location) ~"nigeria_gombe",
    grepl("imo state", 
          location) ~"nigeria_imo",
    grepl("dutse lga|jigawa state",
          location) ~"nigeria_jigawa",
    grepl("goni gora chikun|kaduna state", 
          location) ~"nigeria_kaduna",
    grepl("kano state|gwale lga|gunduwawa gezawa|dawakin tofa",
          location) ~"nigeria_kano",
    grepl("katsina state", 
          location) ~"nigeria_katsina",
    grepl("kebbi state",
          location) ~"nigeria_kebbi",
    grepl("kogi state", 
          location) ~"nigeria_kogi",
    grepl("kwara state",
          location) ~"nigeria_kwara",
    grepl("lagos state", 
          location) ~"nigeria_lagos",
    grepl("keffi lgc|nasarawa state",
          location) ~"nigeria_nassarawa",
    grepl("niger state", 
          location) ~"nigeria_niger",
    grepl("ogun state",
          location) ~"nigeria_ogun",
    grepl("ondo state", 
          location) ~"nigeria_ondo",
    grepl("osun state", 
          location) ~"nigeria_osun",
    grepl("oyo state", 
          location) ~"nigeria_oyo",
    grepl("plateau state|jos north|maraban jos|rayfield jos south", 
          location) ~"nigeria_plateau",
    grepl("port harcourt|rivers state|nkpor obio nkpor lgc", 
          location) ~"nigeria_rivers",
    grepl("sokoto state", 
          location) ~"nigeria_sokoto",
    grepl("taraba state",
          location) ~"nigeria_taraba",
    grepl("yobe state",
          location) ~"nigeria_yobe",
    grepl("zamfara state", 
          location) ~"nigeria_zamfara",
    
    grepl('bosnia - herzegovina',
          location) ~ 'bosnia and herzegovina',
    
    grepl('sva |^sva$|north america|zeebrugge belgi',
          location) ~ 'NA',
    
    # Indonesia
    grepl("hulu sungai utara|banjarbaru", 
          location) ~ "indonesia_kalimantan selatan",
    
    #SA
    grepl("al qasim", 
          location) ~ "saudi arabia_al qassim",
    grepl("riyadh", 
          location) ~ "saudi arabia_ar riyad",
    
    # Other
    grepl("republic of georgia", location) ~ "georgia",
    grepl("czech republic|czechia|czech reublic", location) ~ "czechia",
    grepl("burkina faso|burkina-faso", location) ~ "burkina faso",
    grepl('macedonia', location) ~ 'north macedonia',
    grepl('king island', location) ~ 'australia_tasmania',
    grepl('lisbon', location) ~ 'portugal_lisboa',
    .default = location
  ))

countries <- geodata %>% 
  filter(is.na(name_1)) %>%
  mutate(match = country) %>%
  filter(ifelse(country == 'china' && grepl('z*', gid_0), F, T))

subdiv1 <- geodata %>% 
  filter(!is.na(name_1)) %>%
   unite('match', c(country, name_1), sep = '_', remove = F) %>%
  filter(ifelse(country == 'china' && grepl('z*', gid_0), F, T))
  
geodata_query <- bind_rows(countries, subdiv1)

# update with republic of georgia (also montana clash)
test %>% 
  pull(location) %>% unique() %>% .[!tolower(.) %in% geodata$country] %>% .[!tolower(.) %in% geodata$name_1]

# update with republic of georgia (also montana clash)
test %>% 
  pull(location) %>% unique() %>% .[!tolower(.) %in% geodata_query$match]

[1] NA                  "an"                "ma"                "me"                "ashanti"          
[6] "ns"                "canada_alberta"    "NA"                "tomsk"             "kerala"           
[11] "p"                 "nl almeerder zand" ""                  "assam"             "victoria"         
[16] "south australia"   "md"                "bolivar"           "magdalena"         "alberta"          
[21] "cordoba"           "ohiggins"  

test_2 <- test %>%
  left_join(geodata_query, by = join_by(location == match))

test_2 <- test %>%
 left_join(countries, by = join_by(location == country)) %>%
  left_join(geodata, by = join_by(location == name_1))