library(tidyverse)
geodata <- read_csv('./gdam_geodata.csv')

test <- metadata_unformatted %>% bind_rows(., .id = 'ref')

if('location_2' %in% colnames(data)){
  test <- test %>%
    # Format source before taxa allocation
    rename(joint_location = location) %>%
    mutate(across(contains('location'), 
                  .fns = ~ gsub("^NA$|^missing$|^unknown$", NA, .x))) %>%
    mutate(location = coalesce(location_3,location_2)) %>%
    select(-joint_location)%>%
    rename(source=host) %>%
    select(-starts_with('host')) %>%
    rename(month.date = date_year_month) %>%
    rename(decimal.date = date_frac)
  
} else{
 test <- test %>%
    mutate(date = parsedate::parse_date(date) %>%
             as.Date()) %>%
    mutate(decimal.date = format(round(decimal_date(date), 2), 
                                 nsmall = 2) ) %>%
    mutate(decimal.date = suppressWarnings(as.double(decimal.date))) %>%
    mutate(month.date = format(date, "%Y-%m"))
}

test <- test %>%
  select(-matches('^date.+')) %>%
  rename_with(.fn = ~gsub('_', '.', .x))%>%
  # Location (iso name and subdivision)
  mutate(location = tolower(location)) %>%
  mutate(location = gsub("[^A-Za-z]", " ", tolower(location))) %>%
  mutate(location =  gsub("\\s+", " ", str_trim(location))) %>%
  mutate(location = case_when(
    
    # Austria
    grepl('burgenland|stegersbach|mattersburg|bad sauerbrunn',
          location) ~ 'burgenland',
    grepl('karnten', 
          location)  ~ 'karnten',
    grepl('niederosterreich|voesendorf|strasshof|stockerau|sollenau|breitensee|biberbach',
          location) ~ "niederösterreich", 
    grepl('sankt poelten|pottschach|neunkirchen|markgrafneusiedl|koenigstetten|klosterneuburg',
          location) ~ "niederösterreich",
    grepl('hof am leithaberge|haringsee|fishamend|bruderndorf|tulln|lower austria',
          location) ~ "niederösterreich",
    grepl('oberosterreich$|sankt georgen|^linz$|oberneukirchen',
          location) ~ "oberösterreich",
    grepl('salzburg', 
          location)  ~ 'salzburg',
    grepl('steiermark|tagnitz|^graz$|eggersdorf|leibnitz', 
          location) ~ "steiermark",
    grepl('tirol$', 
          location)  ~ 'tirol',
    grepl('vorarlberg|voralrberg', 
          location)  ~ "vorarlberg",
    grepl('^wien$|^vienna$|bundesland wien', 
          location) ~ 'wien',
    grepl('carinthia', 
          location) ~ "kärnten",
    
    # Belgium
    grepl('antwerpen',
          location) ~ "antwerpen",
    grepl("brabant wallon",
          location) ~ "brabant wallon",
    grepl("brussels capital region|region de bruxelles capitale",
          location) ~ "brussels-capital region",
    grepl('*hainaut$',
          location) ~ "hainaut",
    grepl('*liege$',
          location) ~ "liege",
    grepl('limburg',
          location) ~ "limburg",
    grepl(' luxembourg', 
          location) ~ "luxembourg",
    grepl("^namur$|province de namur",
          location) ~ "namur",
    grepl('oost vlaanderen',
          location) ~ "oost-vlaanderen",
    grepl('vlaams brabant', 
          location) ~ "vlaams-brabant",
    grepl('west vlaanderen', 
          location) ~ "west-vlaanderen",
    
    # Bulgaria 
    grepl('blagoevgrad', 
          location) ~ "blagoevgrad",
    grepl('burgas$', 
          location) ~ "burgas",
    grepl('dobrich$', 
          location) ~ "dobrich",
    grepl('gabrovo$', 
          location) ~ "gabrovo",
    grepl('haskovo$', 
          location) ~ "haskovo",
    grepl('kardzhali$', 
          location) ~ "kardzhali",
    grepl('kyustendil$', 
          location) ~ "kyustendil",
    grepl('lovech$', 
          location) ~ "lovech",
    grepl('blagoevgrad', 
          location) ~ "blagoevgrad",
    grepl('"pazardzhik"', 
          location) ~ "pazardzhik",
    grepl('pernik', 
          location) ~ "pernik",
    grepl('pleven|slavyanovo', 
          location) ~ "pleven",
    grepl('plovdiv$', 
          location) ~ "plovdiv",
    grepl('^razgrad$', 
          location) ~ "razgrad",
    grepl('^ruse$', 
          location) ~ "ruse",
    grepl('shumen', 
          location) ~ "shumen",
    grepl('silistra', 
          location) ~ "silistra",
    grepl('sliven', 
          location) ~ "sliven",
    grepl('smolyan', 
          location) ~ "smolyan",
    grepl('^sofia$', 
          location) ~ "sofia",
    grepl('sofia-grad', 
          location) ~ "sofia-grad",
    grepl('stara zagora', 
          location) ~ "stara zagora",
    grepl('targovishte', 
          location) ~ "targovishte",
    grepl('varna', 
          location) ~ "varna",
    grepl('veliko tarnovo', 
          location) ~ "veliko tarnovo",
    grepl('^vidin$', 
          location) ~ "vidin",
    grepl('^vratsa$', 
          location) ~ "vratsa",
    grepl('^yambol$', 
          location) ~ "yambol",
    
    # Burkina Faso
    grepl("koubri", 
          location) ~ "kadiogo",
    grepl("gomboussougou", 
          location) ~ "zoundwéogo",
    
    # Cambodia
    grepl("krong phnum penh", 
          location) ~"phnom penh",
    grepl("khett kandal",
          location) ~"kandal",
    grepl("khett prey veng",
          location) ~"prey veaeng",
    grepl("takeo", 
          location) ~"taakaev",
    
    # Chile
    grepl("region de antofagasta", 
          location) ~ "antofagasta",
    
    # Colombia
    grepl("departamento de bolivar", 
          location) ~"bolívar",
    grepl("departamento del choco", 
          location) ~"chocó",
    grepl("departamento de cordoba",
          location) ~"córdoba",
    grepl("departamento del magdalena", 
          location) ~"magdalena",
    
    # Costa Rica
    grepl("provincia de limon",
          location) ~ "limón",
    
    # Croatia
    grepl('koprivnicko krizevacka zupanija', 
          location) ~ "koprivničko-križevačka županija",
    grepl('vukovarsko srijemska zupanija',
          location) ~ "vukovarsko-srijemska županija",
    grepl('sisacko moslavacka zupanija',
          location) ~ "sisačko-moslavačka županija",   
    
    # Denmark
    grepl('region sjaland', 
          location) ~    "sjælland",
    grepl('region syddanmark', 
          location) ~ "syddanmark",
    grepl('region nordjylland', 
          location) ~ "nordjylland",
    grepl('region midtjylland',
          location) ~"midtjylland",
    grepl('*denmark$',
          location) ~ 'denmark',
    
    # Ecuador
    grepl('provincia de manabi', 
          location) ~ "manabí",
    
    # Honduras
    grepl('departamento de atlantida',
          location) ~ "atlántida",
    
    # Hungary
    grepl('bacs kiskun',
          location) ~   "bács-kiskun",
    grepl('csongrad megye', 
          location) ~ "csongrád",
    grepl('bekes megye', 
          location) ~ "békés",
    grepl('hajdu bihar', 
          location) ~ "hajdú-bihar",
    grepl('somogy megye', 
          location) ~  "somogy",
    
    # Iceland
    grepl('westfjords',
          location) ~ "vestfirðir",
    
    # Indonesia
    grepl('east java', 
          location) ~ "jawa timur",
    
    # Iraq
    grepl('muhafazat ninawa',
          location) ~ "ninawa",
    
    # Israel
    grepl('northern district', 
          location) ~ "hazafon",
    
    # Kazakhstan
    grepl('akmola', 
          location) ~ "aqmola oblysy", 
    grepl('kostanay', 
          location) ~ "qostanay oblysy",        
    grepl('north kazakhstan',
          location) ~ "soltüstik quzaqstan oblysy",
    grepl('almaty province', 
          location) ~ "almaty oblysy",
    
    # Latvia
    grepl('jurmala',
          location) ~"jūrmala",
    # Lithuania
    grepl('vilnius', 
          location) ~"vilniaus apskritis",
    # Luxembourg
    grepl('district de grevenmacher', 
          location) ~ "grevenmacher",
    grepl('district de diekirch', 
          location) ~ "diekirch",
    # Mali
    grepl('kati', 
          location) ~ "koulikoro",
    
    # Montenegro
    grepl('skadar lake',
          location) ~ "bar",
    
    # Niger
    grepl('bouza tahoua', 
          location) ~ "tahoua",
    grepl('torodi tillab ri',
          location) ~ "tillabéri",  
    grepl(' zinder$', 
          location) ~ "zinder",
    grepl('maradi$',
          location) ~ "maradi",
    grepl('niamey$', 
          location) ~ "niamey",
    
    # Norway
    grepl('hitra', 
          location) ~ "sør-trøndelag",
    grepl('tromso',
          location) ~"troms",
    
    # Peru
    grepl('departamento de lima', 
          location) ~  "municipalidad metropolitana de lima",      
    grepl('provincia constitucional del callao',
          location) ~"el callao",
    grepl('departamento de tacna',
          location) ~ "tacna",        
    grepl('departamento de ica',
          location) ~  "ica",             
    
    # Portugal
    grepl('distrito de setubal', 
          location) ~ "setúbal",
    
    # Romania
    grepl('judetul timis', 
          location) ~ "timiș",     
    grepl('judetul ilfov', 
          location) ~ "ilfov",      
    grepl('judetul constanta', 
          location) ~ "constanța", 
    grepl('mures ungheni', 
          location) ~ "mureș",     
    grepl('judetul giurgiu', 
          location) ~ "giurgiu",   
    grepl('tulcea',
          location) ~ "tulcea",    
    
    # Senegal
    grepl('region de thies',
          location) ~ 'thiès',
    grepl('djoudj bird sanctuary',
          location) ~ 'saint-louis',
    
    # Slovakia
    grepl('dobrohost', 
          location) ~ "trnavský kraj",
    grepl('kosice',
          location) ~  "košický kraj" ,
    grepl('kalinkovo|petrzalka',
          location) ~"bratislavský kraj",
    
    # South Africa
    grepl('province of the western cape',
          location) ~ "western cape",
    grepl('province of kwazulu natal', 
          location) ~  "kwazulu-natal",
    grepl('province of north west',
          location) ~ "north-west (south africa)",
    
    # Switzerland
    grepl('*zurich$',
          location) ~ "zürich",
    grepl('*ticino$', 
          location) ~ "ticino",    
    grepl('kanton basel stadt|*basel$', 
          location) ~ "basel-stadt",
    grepl('*luzern$', 
          location) ~ "luzern",
    
    # Venezuela
    grepl("estado anzoategui", 
          location) ~ "anzoátegui",
  
    
    
    # Vietnam
    grepl("viet nam", 
          location) ~ "vietnam",
    grepl("quang ninh" ,
          location) ~  "quảng ninh" ,
    grepl('tinh lang son',
          location) ~ "lạng sơn",
    grepl('tinh thanh hoa',
          location) ~ "thanh hóa",
    grepl('nghe an|nhge an', 
          location) ~  "nghệ an", 
    grepl('tinh quang tri',
          location) ~ "quảng trị",
    grepl('nam ha tinh', 
          location) ~ "hà tỉnh",
    grepl('thu do ha noi',
          location) ~ "hà nội, thủ đô",
    
    
    # PRC
    grepl("northern china|peking", 
          location) ~ "beijing", # Interpretation from paper - check with Lu
    grepl("chongqin*", 
          location) ~ "chongqing",
    grepl("shanghai",
          location) ~ "shanghai",
    grepl('tianjing',
          location) ~ 'tianjin',
    grepl('anhui',
          location) ~ 'anhui',
    grepl('^fujain$|^fujian$', 
          location) ~ 'fujian',
    grepl('gansu',
          location) ~ 'gansu',
    grepl('qingyuan|foshan|guangdong',
          location) ~ 'guangdong',
    grepl('guizhou', 
          location) ~ 'guizhou',
    grepl("heinan|hainan", 
          location) ~ "hainan", # confirm 
    grepl("wuhan|hebei", 
          location) ~ "hebei",
    grepl("heilongjiang", 
          location) ~ "heilongjiang",
    grepl("henan|sanmenxia|dongting", 
          location) ~ "henan",
    grepl("hubei",
          location) ~ "hubei",
    grepl("hunan|changsha", 
          location) ~ "hunan",
    grepl("jiangsu|suzhou|xuzhou|^xuyi$",
          location) ~ "jiangsu",
    grepl("jiangxi|ganzhou", 
          location) ~ "jiangxi",
    grepl("jilin", 
          location) ~ "jilin",
    grepl("liaoning",
          location) ~ "liaoning",
    grepl("qinghai", 
          location) ~ "qinghai",
    grepl("shaanxi", 
          location) ~ "shaanxi",
    grepl("shandong|rongcheng", 
          location) ~ "shandong",
    grepl("shanxi|southwestern china",
          location) ~ "shanxi",
    grepl("sichuan",
          location) ~ "sichuan",
    grepl("taiwan|chiayi|taoyuan|pingtung", 
          location) ~ "taiwan",
    grepl("taipei", 
          location) ~ "taipei",
    grepl("yunnan.*", 
          location) ~ "yunnan",
    grepl("zhejiang|hangzhou|nanji$|eastern china",
          location) ~ "zhejiang",
    grepl("guangxi$|guilin|hechi|guangxi zhuang",
          location) ~ "guangxi",
    grepl("inner mongolia|tumuji|nei mongol", 
          location) ~ "nei mongol",
    grepl("ningxia$|ningxia hui", 
          location) ~ "ningxia hui",
    grepl("xinjiang$", 
          location) ~ "xinjiang uygur",
    grepl("xizang$|tibet", 
          location) ~ "xizang",
    grepl("macau",
          location) ~ "macau",
    grepl("hong kong|hongkong",
          location) ~ "hong kong",
    
    
    # Canada
    grepl("^ab$",
          location) ~ "alberta",
    grepl("^bc$", 
          location) ~ "british columbia",
    grepl('^mb$', 
          location) ~'manitoba',
    
    # Czechia
    grepl("jihocesky kraj", 
          location) ~"jihočeský kraj",
    grepl("south moravian region", 
          location) ~"jihomoravský kraj",
    grepl("kralovehradecky kraj", 
          location) ~"královéhradecký kraj",
    grepl("liberecky kraj",
          location) ~"liberecký kraj",
    grepl("morovskoslezsky kraj", 
          location) ~"moravskoslezský kraj",
    grepl("olomoucky kraj",
          location) ~"olomoucký kraj",
    grepl("pardubicky kraj", 
          location) ~"pardubický kraj",
    grepl("plzensky kraj",
          location) ~"plzeňský kraj",
    grepl("hlavni mesto praha", 
          location) ~"praha, hlavní město",
    grepl("stredocesky kraj",
          location) ~"středočeský kraj",
    grepl("ustecky kraj",
          location) ~"ústecký kraj",
    grepl("vysocina kraj",
          location) ~"vysočina",
    grepl("zlinsky kraj",
          location) ~"zlínský kraj",
    grepl("nov hrady by ov", 
          location) ~"české budějovice",
    
    
    # France
    grepl("^france&",
          location) ~"france",
    grepl("^alsace&",
          location) ~"alsace",
    grepl("aquitaine",
          location) ~"aquitaine",
    grepl("auvergne",
          location) ~"auvergne",
    grepl("basse normandie",
          location) ~"basse-normandie",
    grepl("bourgogne", 
          location) ~"bourgogne",
    grepl("brittany",
          location) ~"bretagne",
    grepl("^centre$",
          location) ~"centre",
    grepl("champagne ardenne",
          location) ~"champagne-ardenne",
    grepl("corsica", 
          location) ~"corse",
    grepl("franche comté",
          location) ~"franche-comté",
    grepl("haute normandie", 
          location) ~"haute-normandie",
    grepl("region ile de france",
          location) ~"île-de-france",
    grepl("languedoc roussillon", 
          location) ~"languedoc-roussillon",
    grepl("limousin", 
          location) ~"limousin",
    grepl("region lorraine", 
          location) ~"lorraine",
    grepl("midi pyrenees", 
          location) ~"midi-pyrénées",
    grepl("region nord pas de calais", 
          location) ~"nord - pas-de-calais",
    grepl("region pays de la loire", 
          location) ~"pays de la loire",
    grepl("poitou charentes",
          location) ~"poitou-charentes",
    grepl("rhone alpes", 
          location) ~"rhône-alpes",
    grepl("guadeloupe", 
          location) ~"guadeloupe",
    grepl("guyane", 
          location) ~"guyane",
    grepl("martinique", 
          location) ~"martinique",
    grepl("réunion",
          location) ~"réunion",
    grepl("ain", 
          location) ~"ain",
    grepl("aisne", 
          location) ~"aisne",
    grepl("allier",
          location) ~"allier",
    
    
    # Italy
    grepl("emilia romagna", 
          location) ~"emilia-romagna",
    grepl("lombardy",
          location) ~"lombardia",
    grepl("^bs$", 
          location) ~"brescia",
    grepl("^cr$", 
          location) ~"cremona",
    grepl("^mn$", 
          location) ~"mantova",
    grepl("^pd$",
          location) ~"padova",
    grepl("^ud$",
          location) ~"udine",
    grepl("^ve$", 
          location) ~"venezia",
    grepl("^vr$", 
          location) ~"verona",
    grepl("^vi$", 
          location) ~"vicenza",
    
    # Kosovo (Currently represented as serbia)
    grepl('gjilan',
          location) ~ "kosovsko-pomoravski okrug",  
    grepl('mitrovice|mitrovica', 
          location) ~ "kosovsko-mitrovački okrug",
    grepl('shtime|rahovec|malisheve',
          location) ~ "pećki okrug",
    grepl('kacanik|ferizaj|shtime|suhareke',
          location) ~ "kosovski okrug",
    grepl('kosovo', 
          location) ~   "kosovo-metohija",
    
    # Russian Federation
    grepl('russian federation', 
          location) ~ 'russia',
    grepl('khabarovsk', 
          location) ~ "khabarovsk",
    grepl('chelyabinsk', 
          location) ~ "chelyabinsk",
    grepl("astrakhan", 
          location) ~ "astrakhan'",
    grepl("novosibirsk|chany lake|^chany$", 
          location) ~ "novosibirsk",
    grepl("^omsk.*", 
          location) ~ "omsk",
    grepl("rostov oblast|rostov on don|^rostov$", 
          location) ~ "rostov",
    grepl("russia primorje", 
          location) ~ "primor'ye",
    grepl("sakhalin", 
          location) ~ "sakhalin",
    grepl("yakutia", 
          location) ~ "sakha",
    grepl("kostrom*", 
          location) ~ "kostroma",
    grepl("amur region", 
          location) ~ "amur",
    grepl("buryatia", 
          location) ~ "buryat",
    grepl('north ossetia-alania', 
          location) ~ 'north ossetia',
    grepl('dagestan', 
          location) ~ 'dagestan',
    grepl('stavropol', 
          location) ~ "stavropol'",
    grepl('krasnodar', 
          location) ~ "krasnoyarsk", 
    grepl('tyumen', 
          location) ~ "tyumen'",
    grepl("magadan",
          location) ~ "magadan",
    grepl('saratov', 
          location) ~ "saratov",
    grepl('kurgan*', 
          location) ~ "kurgan",
    grepl('central russia',
          location) ~ 'russia',
    grepl('republic of tatarstan|^tatarstan$', 
          location) ~"tatarstan",
    grepl('republic of kalmykia|^kalmykia$', 
          location) ~ "kalmyk",
    grepl('siberia', 
          location) ~ "krasnoyarsk",
    
    grepl('^tuva$|^tyva$|uvs nuur lake', 
          location) ~ "tyva, respublika [tuva]",
    
    grepl('kaliningra{0,1}d', 
          location) ~ "kaliningrad",
    grepl('cheboksary', 
          location) ~ "chuvash",
    grepl('kursk', 
          location) ~ "kursk",
    grepl('sergiyev[[:space:]]{0,1}posad|shchyolkovo|moscow', 
          location) ~ "moskva",
    grepl('kamchatka', 
          location) ~ 'kamchatka',
    grepl('voronezh', 
          location) ~ "voronezht",
    grepl('^orel$', 
          location) ~ "orlov",
    grepl('^penza$', 
          location) ~ "penzen",
    grepl('^samara$', 
          location) ~ "samara",
    grepl('^mari el$', 
          location) ~ 'mariy el, respublika',
    grepl('^leningrad$|leningrad region', 
          location) ~ "leningradskaya oblast",
    grepl('^orenburg$', 
          location) ~ "orenburg oblast",
    grepl('^ryazan$', 
          location) ~ "ryazan'",
    
    
    
    #morocco
    grepl('^fes$', 
          location) ~ 'fès-dar-dbibegh',
    grepl('^casablanca$', 
          location) ~ 'casablanca [dar el beïda]',
    grepl('^kenitra$', 
          location) ~ 'salé',

    
    # Egypt
    grepl('^luxor$', 
          location) ~ 'qinā',
    grepl('^cairo$', 
          location) ~ 'al qāhirah',
    grepl('al sharqia', 
          location) ~ 'ash Sharqīyah',
    grepl('el wadialgidid', 
          location) ~ 'al wādī al jadīd',
    
    
    # USA
    grepl("north dakota",
          location) ~ "north dakota",
    grepl("massachussetts",
          location) ~"connecticut",
    grepl("conneticut",
          location) ~"massachusetts",
    grepl("deleware|delaware", 
          location) ~"delaware",
    grepl('alaska$', location) ~ 'alaska',
    grepl("lou[i]{0,1}siana", location) ~ 'louisiana',
       
 

    # UK
    grepl("wales",
          location) ~ "wales",
    grepl("england",
          location) ~ "united kingdom",
    grepl("county of kent", 
          location) ~ "kent",
    grepl("county borough of wrexham", 
          location) ~ "wrexham;wrecsam",
    grepl("stratford", 
          location) ~ "warwickshire",
    grepl("anglesey",
          location) ~ "isle of anglesey;sir ynys môn",
    grepl("orkney", 
          location) ~ "orkney islands",
    grepl("western isles",
          location) ~ "highland",
    grepl("cheshire", 
          location) ~ "cheshire east",
    grepl("scotland",
          location) ~ "scotland",
    
    # Japan
    grepl("tsukuba", 
          location) ~ "ibaraki",
    grepl('hyogo', 
          location) ~ "hyōgo",
    grepl('nagasaki',
          location) ~ 'naoasaki',
    
    # Spain
    grepl("castilla[ ]{0,1}la[ ]{0,1}mancha|castille[ ]{0,1}la[ ]{0,1}mancha",
          location) ~ "castilla-la mancha",
    
    # Poland
    grepl("lower silesian voivodeship", 
          location) ~"dolnośląskie",
    grepl("kuyavian pomeranian voivodeship",
          location) ~"kujawsko-pomorskie",
    grepl("lublin voivodeship", 
          location) ~"lubelskie",
    grepl("lubusz voivodeship",
          location) ~"lubuskie",
    grepl("lodzkie|odz voivodeship",
          location) ~"łódzkie",
    grepl("lesser poland voivodeship", 
          location) ~"małopolskie",
    grepl("masovian voivodeship",
          location) ~"mazowieckie",
    grepl("opole voivodeship", 
          location) ~"opolskie",
    grepl("pomeranian voivodeship",
          location) ~"pomorskie",
    grepl("silesian voivodeship", 
          location) ~"śląskie",
    grepl("swietokrzyskie voivodeship", 
          location) ~"świętokrzyskie",
    grepl("warmi sko mazurskie",
          location) ~"warmińsko-mazurskie",
    grepl("greater poland voivodeship", 
          location) ~"wielkopolskie",
    grepl("west pomeranian voivodeship",
          location) ~"zachodniopomorskie",
    
    
    # Sweden
    grepl("blekinge lan",
          location) ~"blekinge län",
    grepl("dalarnas lan",
          location) ~"dalarnas län",
    grepl("gotlands lan",
          location) ~"gotlands län",
    grepl("hallands lan", 
          location) ~"hallands län",
    grepl("jonkopings lan"
          , location) ~"jönköpings län",
    grepl("kalmar lan",
          location) ~"kalmar län",
    grepl("skane lan",
          location) ~"skåne län",
    grepl("stockholms lan",
          location) ~"stockholms län",
    grepl("sodermanlands lan", 
          location) ~"södermanlands län",
    grepl("uppsala lan", 
          location) ~"uppsala län",
    grepl("vastra gotalands lan",
          location) ~"västra götalands län",
    grepl("ostergotlands lan", 
          location) ~"östergötlands län",
    
    
    # Germany 
    grepl("^germany$", 
          location) ~"germany",
    grepl("germany[- ]bw|baden wuerttemberg|freiburg im breisgau|rosengarten|stutensee",
          location) ~"baden-württemberg",
    grepl("germany[- ]by|bavaria|munich|nuremberg|wuerzburg", 
          location) ~"bayern",
    grepl("germany[- ]hb", 
          location) ~"bremen",
    grepl("germany[- ]hh", 
          location) ~"hamburg",
    grepl("germany[- ]he|hessen|freigericht|giessen|karben|ranstadt", 
          location) ~"hessen",
    grepl("germany[- ]ni|lower saxony|brietlingen|dinklage|hannover|lueneburg|nordhorn|osnabruck",
          location) ~"niedersachsen", 
    grepl("osterholz[- ]scharnbeck|theene|wingst",
          location) ~"niedersachsen",
    grepl("germany[- ]nw|north rhine[- ]westphalia|aachen|brueggen", 
          location) ~"nordrhein-westfalen",
    grepl("germany[- ]rp|rhineland[- ]palatinate", 
          location) ~"rheinland-pfalz",
    grepl("germany[- ]sl", 
          location) ~"saarland",
    grepl("germany[- ]sh|schleswig[- ]holstein|aumuehle|brickeln|luebeck|pinneberg|prohn", 
          location) ~"schleswig-holstein",
    grepl("germany[- ]be",
          location) ~"berlin",
    grepl("germany[- ]bb", 
          location) ~"brandenburg",
    grepl("germany[- ]mv|mecklenburg[- ]vorpommern|grevesmuehlen|parchim|ruegen|warin", 
          location) ~"mecklenburg-vorpommern",
    grepl("germany[- ]sn|sachsen|doberschuetz|dresden|gross dueben|leipzig|saxony",
          location) ~"sachsen",
    grepl("germany[- ]st|sachsen[- ]anhalt|^halle$|zeitz", 
          location) ~"sachsen-anhalt",
    grepl("germany[- ]th|thuring.*|^gera$", 
          location) ~"thüringen",
    
    
    # Korea
    grepl("korea", 
          location) ~ "south korea",
    grepl('^gg$|gyeonggi*', 
          location) ~ "gyeonggido",
    grepl('^gw$', 
          location) ~ "gang'weondo",
    grepl('^cn$|chungcheongnam*', 
          location) ~ "chungcheongnamdo",
    grepl('^cb$|chungcheongbuk*',
          location) ~ "chungcheongbukdo",
    grepl('^gn$',
          location) ~ "gyeongsangnamdo",
    grepl('^gb$',
          location) ~ "gyeongsangbukdo",
    grepl('^jn$',
          location) ~ "jeonranamdo",
    grepl('^jb$', 
          location) ~ "jeonrabukdo",
    grepl('^jj$',
          location) ~ "jejudo",
    grepl('^sw$', 
          location) ~ "seoul teugbyeolsi", 
    grepl('^ic$',
          location) ~ "incheon gwang'yeogsi", 
    grepl('^dj$',
          location) ~ "daejeon gwang'yeogsi", 
    grepl('^sj$|sejong teugbyeolsi', 
          location) ~ "sejong teugbyeolsi", 
    grepl('^gj$',
          location) ~ "gwangju gwang'yeogsi", 
    grepl('^dg$',
          location) ~ "daegu gwang'yeogsi", 
    grepl('^ps$', 
          location) ~ "busan gwang'yeogsi", 
    grepl('^us$', 
          location) ~ "ulsan gwang'yeogsi", 
    
    
    # Netherlands
    grepl('drenthe|westerveld|borger-odoorn|tynaarlo|eext|koekange|middendrexhe|noordenveld|nl assen',
          location)  ~ 'drenthe',
    grepl('flevoland|almere|lelystad|noordoostpolder|noordosterpolder|marker wadden|stroe waddenkust',
          location) ~ 'flevoland',
    grepl('zeewolde tulpeiland|zuidlaarmeergebiede oost polder|roggebotsluis|zeewolde',
          location) ~ 'flevoland',
    grepl('friesland|fryslan|tytsjerksteradiel|eastermar|heerenveen|schiermonnikoog|^ameland$', 
          location) ~ "friesland",
    grepl('kollum|^vlieland.*|ameland|noord[[:space:]]{0,1}buren waddenkust|greonterp|walterswald|nl abbega|terschelling|leeuwarden', 
          location) ~ "friesland",
    grepl('gelderland|zutphen|zevenaar|westvoort|westervoort|andelst|arnhem|bennekom|deliemers',
          location) ~ 'gelderland',
    grepl('spijk|doetichem|doetinchem|epe|ermelo|gelmonde|ingen|klarenbeek|lochem|oldenbroek|huissen',
          location) ~ 'gelderland',
    grepl('putten|zwolle bergkloosterweg|apeldoorn boogschutterstraat|boven leeuwen|barneveld',
          location) ~ 'gelderland',
    grepl('groningen|zuidhorn|oldambt|spijk|lauwersmeer|haren boeremapark|scheemda|sint annen', 
          location)  ~ 'groningen',
    grepl('limburg|venlo|gennep|kerkrade|landgraaf|ottersum|maastricht',
          location) ~ 'limburg',
    grepl('noord brabant|wernhout|vlijmen|beekendonk|best|boekel|uden|agatha|schaik|rosmalen|^reek&',
          location) ~ 'noord-brabant',
    grepl('lierop|oss|north brabant|oirschot|lithse eendenkooi|werkendam',
          location) ~ 'noord-brabant',
    grepl('noord holland|bloemendaal|heerhugowaard|hilversum|huizen|naarden|reek|texel de schorren|volendam|durgerdam', 
          location) ~ 'noord-holland',
    grepl('wie[r]{0,1}ingerwerf|den oever|hippolytushoef|kreupel|onderdijk|^obdam$|monnickendam|slootdorp|zuidoost beemster', 
          location) ~ 'noord-holland',
    grepl('ijmuiden forteiland|zwaagdijk.*|schellinkhout zuiderdijk|schagen schagerweg|nl wormer$|west graftdijk|oostwoud', 
          location) ~ 'noord-holland',
    grepl('overijssel|wierden|enschede|hardenberg|heino|losser|overdinkel|raalte|ijsselmuiden|nl zwolle|kamperveen|mastenbroek',
          location)  ~ 'overijssel',
    grepl('utrecht|bilthoven|bosch en duin|bunnik|debilt|derondevenen|soest|haarzuilens|houten|rhenen', 
          location)  ~ 'utrecht',
    grepl('ijsselstein|langbroek|nieuwegein|ijsselstein|woerden|leusden|vleuten.*|portengen|eemmeer dode hond|vianen', 
          location)  ~ 'utrecht',
    grepl('zeeland|terneuzen|reimerswaal|grenspad|middelburg|weversinlaag|weversinlaag|neeltje jans', 
          location) ~ 'zeeland',
    grepl('walcheren t vroon westkapelle|sloehaven', 
          location) ~ 'zeeland',
    grepl('zuid holland|zoeterwoude|westland|den haag|rotterdam|rijswijk|leiden|oud albas|oud alblas',
          location) ~ 'zuid-holland',
    grepl('nederlek|hardinxveldgiessendam|south holland|eendenkooi stolwijk|haringvliet|bliek$', 
          location) ~ 'zuid-holland',
    grepl('kwade hoek stellendam|stellendam scheelhoekeiland|leidschendam|nl gouda|groot ammers|reeuwijk|stolwijk', 
          location) ~ 'zuid-holland',
    grepl('^nl$|nl sovon', location) ~ 'netherlands',
    
    
    # Nigeria
    grepl("abuja",
          location) ~"abuja capital territory",
    grepl("abia state", 
          location) ~"abia",
    grepl("adamawa state",
          location) ~"adamawa",
    grepl("akwa ibom state", 
          location) ~"akwa ibom",
    grepl("aguata lga|anambra state",
          location) ~"anambra",
    grepl("tilden fulani toro lga|bauchi state", 
          location) ~"bauchi",
    grepl("bayelsa state", 
          location) ~"bayelsa",
    grepl("benue state", 
          location) ~"benue",
    grepl("borno state", 
          location) ~"borno",
    grepl("corss river state", 
          location) ~"cross river",
    grepl("delta state",
          location) ~"delta",
    grepl("ebonyi state", 
          location) ~"ebonyi",
    grepl("benin edo|edo state", 
          location) ~"edo",
    grepl("ekiti state",
          location) ~"ekiti",
    grepl("enugu state", 
          location) ~"enugu",
    grepl("gombe state|pantaini lbm|^akko[ gombe]{0,1}", 
          location) ~"gombe",
    grepl("imo state", 
          location) ~"imo",
    grepl("dutse lga|jigawa state",
          location) ~"jigawa",
    grepl("goni gora chikun|kaduna state", 
          location) ~"kaduna",
    grepl("kano state|gwale lga|gunduwawa gezawa|dawakin tofa",
          location) ~"kano",
    grepl("katsina state", 
          location) ~"katsina",
    grepl("kebbi state",
          location) ~"kebbi",
    grepl("kogi state", 
          location) ~"kogi",
    grepl("kwara state",
          location) ~"kwara",
    grepl("lagos state", 
          location) ~"lagos",
    grepl("keffi lgc|nasarawa state",
          location) ~"nassarawa",
    grepl("niger state", 
          location) ~"niger",
    grepl("ogun state",
          location) ~"ogun",
    grepl("ondo state", 
          location) ~"ondo",
    grepl("osun state", 
          location) ~"osun",
    grepl("oyo state", 
          location) ~"oyo",
    grepl("plateau state|jos north|maraban jos|rayfield jos south", 
          location) ~"plateau",
    grepl("port harcourt|rivers state|nkpor obio nkpor lgc", 
          location) ~"rivers",
    grepl("sokoto state", 
          location) ~"sokoto",
    grepl("taraba state",
          location) ~"taraba",
    grepl("yobe state",
          location) ~"yobe",
    grepl("zamfara state", 
          location) ~"zamfara",
    
    grepl('bosnia - herzegovina',
          location) ~ 'bosnia and herzegovina',
    
    grepl('sva |^sva$|north america|zeebrugge belgi',
          location) ~ 'NA',
    
    # Indonesia
    grepl("hulu sungai utara|banjarbaru", 
          location) ~ "kalimantan selatan",
    
    #SA
    grepl("al qasim", 
          location) ~ "al qaşīm",
    grepl("riyadh", 
          location) ~ "ar riyāḍ",
   
    #
    
    # Other
    grepl("republic of georgia", location) ~ "georgia",
    grepl("czech republic|czechia", location) ~ "czechia",
    grepl("burkina faso", location) ~ "burkina-faso",

   # al sharqia 
    
    # grepl('laos', location) ~ "lao people's democratic republic",
    
    .default = location
  )) %>%
  mutate(location = case_when(    
    location == "ain" ~ 'spain',
    .default = location))

# update with republic of georgia (also montana clash)
test %>% 
  pull(location) %>% unique() %>% .[!tolower(.) %in% geodata$country] %>% .[!tolower(.) %in% geodata$name_1]

countries <- geodata %>% 
  filter(is.na(name_1)) %>%
  select(-c(ends_with('1'), starts_with('adm1'))) %>%
  filter(ifelse(country == 'china' & grepl('z*', gid_0), F, T))

test_2 <- test %>%
 left_join(countries, by = join_by(location == country)) %>%
  left_join(geodata, by = join_by(location == name_1))